In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Torch

In [2]:
import torch

x = torch.empty(3)
print(x)

tensor([-6.7253e+06,  4.4997e-41, -6.7253e+06])


In [3]:
x = torch.empty(2,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [4]:
x = torch.rand(2,2)
print(x)

tensor([[0.9463, 0.4092],
        [0.4553, 0.5537]])


In [5]:
x = torch.zeros(2,2)
print(x)

tensor([[0., 0.],
        [0., 0.]])


In [6]:
x = torch.ones(2,2)
print(x)

tensor([[1., 1.],
        [1., 1.]])


In [7]:
x = torch.ones(2,2, dtype = torch.int)
print(x.dtype)

torch.int32


In [8]:
x = torch.ones(2,2, dtype = torch.int)
print(x.size())

torch.Size([2, 2])


# Tensors

In [9]:
x = torch.tensor([2.5,0.1])
print(x)

tensor([2.5000, 0.1000])


In [10]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)
z=x+y
z = torch.add(x,y)
print(z)

tensor([[0.3285, 0.8428],
        [0.7157, 0.2388]])
tensor([[0.2662, 0.3568],
        [0.1101, 0.1217]])
tensor([[0.5947, 1.1996],
        [0.8258, 0.3605]])


In [11]:
x = torch.rand(2,2)
y = torch.rand(2,2)
y.add_(x) #trailing _ will modify the value
print(y)

tensor([[1.2956, 1.6199],
        [1.7463, 1.6919]])


In [12]:
x = torch.rand(2,2)
y = torch.rand(2,2)
z=x*y
z=torch.mul(x,y)
y.mul_(x)

tensor([[0.4447, 0.6124],
        [0.0205, 0.1200]])

In [13]:
x = torch.rand(5,3)
print(x)
print(x[:, 0])
print(x[1,:])
print(x[1, 1])
print(x[1, 1].item()) #get's actual value but only works with one value in there

tensor([[0.9823, 0.1399, 0.7306],
        [0.8263, 0.9919, 0.7467],
        [0.7093, 0.5334, 0.8946],
        [0.8184, 0.3281, 0.9615],
        [0.9967, 0.5863, 0.9333]])
tensor([0.9823, 0.8263, 0.7093, 0.8184, 0.9967])
tensor([0.8263, 0.9919, 0.7467])
tensor(0.9919)
0.9919249415397644


In [14]:
x=torch.rand(4,4)
print(x)
y=x.view(16)
print(y.size())

tensor([[0.8645, 0.6464, 0.0449, 0.9622],
        [0.9407, 0.9999, 0.7684, 0.1569],
        [0.4358, 0.5819, 0.3915, 0.9096],
        [0.1433, 0.2386, 0.3000, 0.7814]])
torch.Size([16])


In [15]:
a = torch.ones(5)
print(a)
b=a.numpy()
print(b)

a.add_(1)
print(a)
print(b) #same memory location

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [16]:
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [17]:
a+=1
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [18]:
if torch.cuda.is_available(): #for gpu instead of cpu
    device = torch.device("cuda")
    x = torch.ones(5, device=device)
    y = torch.ones(5)
    y = y.to(device)
    z = x+y
    z.to("cpu") #to get back to cpu
print(z)

tensor([[0.4447, 0.6124],
        [0.0205, 0.1200]])


In [19]:
x = torch.ones(5, requires_grad = True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)


# Homework part

In [20]:
x = torch.tensor([1.0, 2.0, 3.0])
print(x.shape, x.dtype)

t = torch.from_numpy(np.array([1, 2, 3]))
print(t)

a = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
b = torch.tensor([[5.0, 6.0], [7.0, 8.0]])
print(a @ b)   # matrix multiply — you'll use this constantly

torch.Size([3]) torch.float32
tensor([1, 2, 3])
tensor([[19., 22.],
        [43., 50.]])
